apiVersion: v1
kind: Secret
metadata:
  name: {{ template "flectra.fullname" . }}
  labels:
    app: {{ template "flectra.name" . }}
    chart: {{ template "flectra.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
type: Opaque
data:
  {{ if .Values.flectraPassword }}
  flectra-password: {{ .Values.flectraPassword | b64enc | quote }}
  {{ else }}
  flectra-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{ end }}
  {{ if .Values.smtpPassword }}
  smtp-password: {{ .Values.smtpPassword | b64enc | quote }}
  {{ end }}
