apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgresql
  name: postgres
spec:
  ports:
  - name: postgresql
    port: 5432
    protocol: TCP
    targetPort: postgresql
  selector:
    app: postgresql
    role: master
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
